syntax enable
set modelines=1

set tabstop=2
set softtabstop=2
set expandtab

set showcmd
set cursorline

filetype indent on
set wildmenu
set showmatch

set hlsearch

set awa

set foldenable
set foldmethod=indent
set foldlevel=99

nnoremap <leader>u :GundoToggle<CR>
